# Generated by Django 5.2.6 on 2025-10-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Title (AR)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (AR)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
