# Generated by Django 5.2.6 on 2025-10-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VISTA', '0002_section_course_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbs/', verbose_name='Thumbnail'),
        ),
    ]
