# Generated by Django 5.2.6 on 2025-10-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VISTA', '0003_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_1', models.CharField(blank=True, max_length=30, verbose_name='Phone 1')),
                ('phone_2', models.CharField(blank=True, max_length=30, verbose_name='Phone 2')),
                ('phone_3', models.CharField(blank=True, max_length=30, verbose_name='Phone 3')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address_en', models.CharField(blank=True, max_length=255, verbose_name='Address (EN)')),
                ('address_ar', models.CharField(blank=True, max_length=255, verbose_name='Address (AR)')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram URL')),
            ],
        ),
    ]
