# Generated by Django 5.2.6 on 2025-10-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VISTA', '0004_locationdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationdetail',
            options={'verbose_name': 'Institute Information', 'verbose_name_plural': 'Institute Information'},
        ),
    ]
