# Generated by Django 5.2.6 on 2025-10-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VISTA', '0007_alter_message_options_message_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField(blank=True)),
                ('num2', models.IntegerField(blank=True)),
                ('num3', models.IntegerField(blank=True)),
                ('num4', models.IntegerField(blank=True)),
            ],
        ),
    ]
