# Generated by Django 5.2.6 on 2025-10-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VISTA', '0008_statics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statics',
            name='num1',
            field=models.IntegerField(blank=True, verbose_name='New Students'),
        ),
    ]
