# Generated by Django 5.2.6 on 2025-10-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VISTA', '0009_alter_statics_num1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statics',
            name='num2',
            field=models.IntegerField(blank=True, verbose_name='Succesed Students'),
        ),
        migrations.AlterField(
            model_name='statics',
            name='num3',
            field=models.IntegerField(blank=True, verbose_name='Current Teachers'),
        ),
        migrations.AlterField(
            model_name='statics',
            name='num4',
            field=models.IntegerField(blank=True, verbose_name='Awards'),
        ),
    ]
