# Generated by Django 5.2.6 on 2025-10-29 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VISTA', '0010_alter_statics_num2_alter_statics_num3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Title (AR)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (AR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='diploma_thumbs/', verbose_name='Thumbnail')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diploma', to='VISTA.section')),
            ],
        ),
    ]
