# Generated by Django 5.2.6 on 2025-11-04 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VISTA', '0011_diploma'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdetail',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='locationdetail',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only the most recent active record will be displayed', verbose_name='Active'),
        ),
    ]
